import type { Metadata } from "next";
import "./globals.css";
import "../public/logo.png";
import { outfit } from "@/public/fonts";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "mediator.",
  description: "Generated by create next app",
  icons: "logo.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
